# Generated by Django 3.1.1 on 2021-02-14 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('Requirement', 'An application requirement'), ('DataItemType', 'a data item type'), ('EnumItem', 'An enumerated item'), ('DataItem', 'a data item'), ('Model', 'A behavioural model for an application feature'), ('Service', 'A cordet service'), ('Packet', 'A packet implementing a service command or report'), ('DerPacket', 'A derived packet'), ('PacketPar', 'A parameter in a packet'), ('InCommand', 'The behaviour associated to an incoming service command'), ('InReport', 'The behaviour associated to an incoming service report'), ('OutComponent', 'The behaviour associated to an out-going service command or report'), ('VerItem', 'A verification item')], max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DEL', 'Deleted'), ('OBS', 'Obsolete'), ('CNF', 'Confirmed'), ('MOD', 'Modified'), ('NEW', 'New')], default='NEW', max_length=20)),
                ('updated_at', models.DateTimeField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('p_kind', models.CharField(choices=[('STD', 'Standard Requirement'), ('CNS', 'Constraint Requirement'), ('AP', 'Adaptation Point Requirement'), ('CNS', 'Constant'), ('PAR', 'Configuration Parameter'), ('VAR', 'Global Variable'), ('PCK', 'Packet Parameter'), ('ENUM', 'Enumerated'), ('NOT_ENUM', 'Not Enumerated'), ('SM', 'State Machine'), ('PR', 'Procedure'), ('REP', 'Report'), ('CMD', 'Command'), ('DISC', 'Discriminant'), ('HK', 'Housekeeping Parameter'), ('PCK', 'Packet Parameter'), ('PROV', 'Service Provider'), ('USER', 'Service User'), ('TST', 'Test Case'), ('REV', 'Review Item'), ('ANA', 'Analysis Item')], max_length=24)),
                ('s_kind', models.CharField(choices=[('OPEN', 'Verification Still Open'), ('CLOSED', 'Verification Closed')], max_length=24)),
                ('value', models.TextField(blank=True, default='')),
                ('t1', models.TextField(blank=True, default='')),
                ('t2', models.TextField(blank=True, default='')),
                ('t3', models.TextField(blank=True, default='')),
                ('t4', models.TextField(blank=True, default='')),
                ('t5', models.TextField(blank=True, default='')),
                ('n1', models.IntegerField(blank=True, default=0)),
                ('n2', models.IntegerField(blank=True, default=0)),
                ('n3', models.IntegerField(blank=True, default=0)),
                ('application', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_spec_items', to='editor.application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_spec_items', to=settings.AUTH_USER_MODEL)),
                ('p_link', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p_children', to='editor.specitem')),
                ('previous', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='editor.specitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_spec_items', to='editor.project')),
                ('s_link', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='s_children', to='editor.specitem')),
            ],
        ),
        migrations.CreateModel(
            name='VerItemToSpecItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, default='')),
                ('spec_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ver_item_links', to='editor.specitem')),
                ('ver_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spec_item_links', to='editor.specitem')),
            ],
        ),
        migrations.CreateModel(
            name='ValSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(default='Default', max_length=24)),
                ('desc', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='val_sets', to='editor.project')),
            ],
        ),
        migrations.AddField(
            model_name='specitem',
            name='val_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='val_set_spec_items', to='editor.valset'),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('updated_at', models.DateTimeField()),
                ('project_version', models.PositiveSmallIntegerField(default='0')),
                ('application_version', models.PositiveSmallIntegerField(default='0')),
                ('previous', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='editor.release')),
                ('release_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_users', to='editor.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editor.release'),
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='editor.project'),
        ),
        migrations.AddField(
            model_name='application',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='editor.release'),
        ),
    ]
