# Generated by Django 3.1.1 on 2021-01-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='specitem',
            name='cat',
            field=models.CharField(choices=[('Requirement', 'An application requirement'), ('DataItemType', 'a data item type'), ('EnumItem', 'An enumerated item'), ('DataItem', 'a data item'), ('Model', 'A behavioural model for an application feature'), ('Service', 'A cordet service'), ('Packet', 'A packet implementing a service command or report'), ('PacketPar', 'A parameter in a packet'), ('PacketBehaviour', 'The behaviour associated to a packet in an application'), ('VerItem', 'A verification item')], max_length=24),
        ),
    ]
