# Generated by Django 3.1.7 on 2021-03-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('RO', 'Read-Only'), ('RW', 'Read-Write')], default='RO', max_length=24),
        ),
    ]
