# Generated by Django 3.1.1 on 2021-01-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20210120_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='specitem',
            name='dim',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
