# Generated by Django 3.1.7 on 2021-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_projectuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='specitem',
            name='change_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
