# Generated by Django 3.1.1 on 2021-01-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_specitem_dim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetpar',
            name='order',
        ),
    ]
