# Generated by Django 2.2.12 on 2021-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_specitem_implementation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specitem',
            name='cat',
            field=models.CharField(choices=[('Requirement', 'An application requirement'), ('AdaptPoint', 'An adaptation point'), ('DataItemType', 'A non-enumerated data item type'), ('EnumType', 'An enumerated data item type'), ('EnumValue', 'An enumerated item'), ('DataItem', 'A data item'), ('Model', 'A behavioural model for an application feature'), ('Service', 'A cordet service'), ('Packet', 'A packet implementing a service command or report'), ('DerPacket', 'A derived packet'), ('PacketPar', 'A parameter in a packet'), ('InCommand', 'The behaviour associated to an incoming service command'), ('InReport', 'The behaviour associated to an incoming service report'), ('OutComponent', 'The behaviour associated to an out-going service command or report'), ('VerItem', 'A verification item'), ('VerLink', 'A verification link')], max_length=24),
        ),
        migrations.DeleteModel(
            name='VerItemToSpecItem',
        ),
    ]
