# Generated by Django 3.1.7 on 2021-07-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20210718_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cluster',
            new_name='cats',
        ),
    ]
