# Generated by Django 3.1.7 on 2021-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_auto_20210721_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cats',
            field=models.TextField(),
        ),
    ]
