# Generated by Django 3.1.7 on 2021-10-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20210721_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cats',
            field=models.TextField(default=''),
        ),
    ]
