# Generated by Django 3.1.7 on 2021-12-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_application_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='specitem',
            name='s_data',
            field=models.JSONField(default=dict),
        ),
    ]
