# Generated by Django 3.2.15 on 2023-09-05 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_specitem_s_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='specitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
